version: '2' # required to adjust maintainability checks
exclude_patterns:
  - '**/*.test.js'
  - 'seed.js'
  - 'seed.sql'
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    enabled: false
  file-lines:
    config:
      threshold: 250
  method-complexity:
    enabled: false
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 45
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  editorconfig:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  stylelint:
    enabled: true
